# Generated by Django 6.0.2 on 2026-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='email',
        ),
        migrations.AddField(
            model_name='merchant',
            name='MID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='SNO',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='TID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
