# Generated by Django 6.0.2 on 2026-03-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_remove_merchant_email_merchant_mid_merchant_sno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='TID',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
