# Generated by Django 6.0.2 on 2026-03-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('IT-TEAM', 'It-team'), ('SUPPORT', 'Support')], max_length=20),
        ),
    ]
