# Generated by Django 6.0.2 on 2026-03-04 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='pos_name',
        ),
        migrations.AddField(
            model_name='pos',
            name='MID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_id', to='merchants.merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pos',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_pos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
