# Generated by Django 6.0.2 on 2026-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ticket_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
