# Generated by Django 6.0.2 on 2026-03-04 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_ticket_number'),
        ('merchants', '0001_initial'),
        ('pos', '0002_remove_pos_pos_name_pos_mid_pos_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='MID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_id_no', to='merchants.merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='SNO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serial_number', to='pos.pos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='TID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_id', to='pos.pos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_name', to='merchants.merchant'),
        ),
    ]
